version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=master;User=SA;Password=Task123!@#;TrustServerCertificate=True
    restart: always
  db:  
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=SA
      - SA_PASSWORD=Task123!@#
    ports:
      - 5545:1433